### PR TITLE
Renew rspec syntax

### PR DESCRIPTION
**Pull request by styd**
- Use rspec recommended `:expect` method to replace the now deprecated `:should`.
  <br />\* Change `stub` from rspec-mocks' old `:should` syntax to `:allow`.

### CODE REVIEW

**Comment by apraditya** [comment]
Sorry for the late response. Just saw this. Will merge ASAP.

**Comment by styd** [comment]
Thank you. I just reopened the pull requests. Let me know if I can improve my changes in some way to meet your style or expectation.

**Comment by apraditya** [comment]
Looks good. Please rebase to master. Thanks

**Comment by styd** [comment]
Okay. I will close this PR and PR another one.

**Pull request closed without merging**
